### ISSUE TITLE
Email body is empty!

### ISSUE THREAD

**Issue by aravindc26** [netneutrality/savetheinternet.in#21] opened 2015-04-11 15:03 UTC
I clicked on edit responses to check the mail body.. and when chose gmail the body did not get filled in the composer.. !!

**Comment by knightsamar** [comment] 2015-04-11 15:04
Did you try copy pasting ? The text might be in your clipboard. What browser and platform are you on btw?

**Comment by gargsms** [comment] 2015-04-11 17:02
@aravindc26 You need to paste it yourself.

Please close this issue.

![screenshot from 2015-04-11 22 30 17](https://cloud.githubusercontent.com/assets/5238955/7102336/88bc6c7e-e09a-11e4-8ae9-d60c8faa9952.png)

**Comment by sudheesh001** [comment] 2015-04-12 07:10
The actual behaviour that is generally expected by the user is for the content to load automatically in the body which isn't happening right now. One thing to remember is that users want minimal effort while achieving maximum impact.

Right now, it took my friends quite some time to realise that the content was on their clipboard and expected the content to be there automatically. This could be seen as a request for an enhancement.

As far as the issue is concerned, it could be safely closed.

**Closed** 2015-04-12 08:07 UTC

**Comment by miteshashar** [comment] 2015-04-12 08:09
We are looking at pushing a better alternative version of the UI soon. That shall be expected to handle all these issues.

**Comment by aravindc26** [comment] 2015-04-12 12:22
My bad, did not notice it !
