### ISSUE TITLE
Spaces gets converted to escape characters

### ISSUE THREAD

**Issue by srikanthlogic** [netneutrality/savetheinternet.in#33] opened 2015-04-11 18:46 UTC
When you click that send and it goes in my gmail app, all the empty lines gets converted to \0AD characters:
For example :
""Question 4: Should the Internet/OTT players pay for use of the Telecom Operators network over and above data charges paid by consumers? If yes, what pricing options can be adopted? Could such options include prices based on bandwidth consumption? Can prices be used as a means of product/service differentiation? Please comment with justifications.%0D%0A%0D%0AAs I argue in my answers above, telecom"""

Google chrome in Android lollipop 5.02

**Comment by karthikb351** [comment] 2015-04-11 18:48
Duplicate of #12 .

**Closed by karthikb351** 2015-04-11 18:48 UTC
