### ISSUE TITLE
Mrs. Meenakashi Lekhi

### ISSUE THREAD

**Issue by sachin26** [netneutrality/savetheinternet.in#117] opened 2015-12-24 19:42 UTC
meenakashi.lekhi@sansad.nic.in

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain sansad.nic.in by mailgw.nic.in.

**Comment by knightsamar** [comment] 2015-12-25 06:54
Could you paste the full error message on pastebin or something like that and give a link to it ? It seems to be the official address as listed on Sansad's member page: http://164.100.47.192/Loksabha/Members/MemberBioprofile.aspx?mpsno=4717

**Comment by miteshashar** [comment] 2015-12-26 08:59
Duplicate of #106

**Closed** 2015-12-26 09:10 UTC

**Comment by sachin26** [comment] 2015-12-26 09:11
But her gmail id is working

http://pastebin.com/1HbjNFrg

**Comment by miteshashar** [comment] 2015-12-26 09:16
Haven't removed her gmail id. Only the sansad.nic.in id.
